### ISSUE TITLE
Marker Direction

### ISSUE THREAD

**Issue by dt-ap** [hugobarragon/leaflet-drift-marker#2]
Is there a way to animate marker direction?? (Ex: Uber/Lyft or Waze/GMaps direction). So if I make an arrow marker, the head always pointed to the direction it moves

**Comment by hugobarragon** [comment]
> Is there a way to animate marker direction?? (Ex: Uber/Lyft or Waze/GMaps direction). So if I make an arrow marker, the head always pointed to the direction it moves

yes, for that you would have to use another plugin like: [leaflet-rotatedmarker](https://www.npmjs.com/package/leaflet-rotatedmarker)

here you have an example (I am still trying to figure the math angle):
in this example the icon rotates with no problem, just figure out how to calculate the angle between the two coordinates.
[![Edit react-leaflet_DriftMarker-rotate](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-leafletdriftmarker-qsoo0?fontsize=14&hidenavigation=1&theme=dark)

For me to do it right, I would extend the drift marker react component. [DriftMarker](https://github.com/hugobarragon/leaflet-drift-marker/blob/master/src/DriftMarker/DriftMarker.tsx)

or I would extend the Drift marker itself to join this two plugins, if you need any more help just ask [Drift_Marker](https://github.com/hugobarragon/leaflet-drift-marker/blob/master/src/DriftMarker/Drift_Marker.ts)

**Comment by hugobarragon** [comment]
> Is there a way to animate marker direction?? (Ex: Uber/Lyft or Waze/GMaps direction). So if I make an arrow marker, the head always pointed to the direction it moves

yes, for that you would have to use another plugin like: [leaflet-rotatedmarker](https://www.npmjs.com/package/leaflet-rotatedmarker)

here you have an example (I am still trying to figure the math angle):
in this example the icon rotates with no problem, just figure out how to calculate the angle between the two coordinates.
[![Edit react-leaflet_DriftMarker-rotate](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-leafletdriftmarker-qsoo0?fontsize=14&hidenavigation=1&theme=dark)

For me to do it right, I would extend the drift marker react component. [DriftMarker](https://github.com/hugobarragon/leaflet-drift-marker/blob/master/src/DriftMarker/DriftMarker.tsx)

or I would extend the Drift marker itself to join this two plugins, if you need any more help just ask [Drift_Marker](https://github.com/hugobarragon/leaflet-drift-marker/blob/master/src/DriftMarker/Drift_Marker.ts)
