### ISSUE TITLE
leaflet-drift-marker does not work with react-leaflet v3

### ISSUE THREAD

**Issue by MariosPalazis** [hugobarragon/leaflet-drift-marker#5]
I follow the demo instructions with react hooks but I got the error TypeError: Object prototype may only be an Object or null: undefined.  Or some times couldnt read "lat". I attach some snippets
![er2](https://user-images.githubusercontent.com/56583171/110466149-092d7080-80de-11eb-8808-3a3b0aef7f30.jpg)
![er3](https://user-images.githubusercontent.com/56583171/110466153-0a5e9d80-80de-11eb-8f2d-57331df2df79.jpg)
![er1](https://user-images.githubusercontent.com/56583171/110466164-0fbbe800-80de-11eb-9721-e9e357619e7a.jpg)

**Comment by hugobarragon** [comment]
@MariosPalazis list the versions you are using please  
but your import should be as the documentacion show
`import { DriftMarker } from "leaflet-drift-marker"`
create a code sandobox link to replicate the bugm use the demo link to replicate

**Comment by MariosPalazis** [comment]
"core-js": "^3.9.1",
    "leaflet": "^1.7.1",
    "leaflet-drift-marker": "^1.0.3",
    "react": "^17.0.1",
    "react-dom": "^16.14.0",
    "react-leaflet": "^3.1.0",
    "react-leaflet-animated-marker": "^1.0.2",

I did it like this: import { DriftMarker } from "leaflet-drift-marker"
..same error

**Comment by hugobarragon** [comment]
ok you are using react-leaflet new version 3.x its not supported as stated on documentation only previous non hooks version 2.x is supported or now

https://github.com/hugobarragon/leaflet-drift-marker/blob/master/README.md

**Comment by hugobarragon** [comment]
## READ WITH ATENTION

This Repo will only create the leaflet pure class, to use with leaflet, and for other frameworks to use, such as react,vue,angular....
this wil

for react usage it will be created a react-leaflet-drift-marker that will integrate leaflet-drift-marker

with this we can split features and make bundle size smaller for every framework and user needs

**Comment by hugobarragon** [comment]
Moved to https://github.com/hugobarragon/react-leaflet-drift-marker

**Comment by hugobarragon** [comment]
react-leaflet-drift-marker v3 will support react-leaflet v3
