### ISSUE TITLE
drift_marker is not a constructor

### ISSUE THREAD

**Issue by wajahataliawan** [hugobarragon/leaflet-drift-marker#6]
i am using drift_marker but facing issue while i using these line of code.
 marker = new Drift_Marker([Arrlat[0], Arrlng[0]], {
                draggable: true,
                title: "Resource location",
                alt: "Resource Location",
                riseOnHover: true
            }).addTo(map)
                .bindPopup("test").openPopup();

please consider.

**Comment by hugobarragon** [comment]
Hi, @wajahataliawan please provide a reproducible link, you can use this template, and upload here the error logs
https://codesandbox.io/s/static-bcdhq?fontsize=14
