### ISSUE TITLE
SlideTo()  - the endpoint not accurate

### ISSUE THREAD

**Issue by Rehum02** [hugobarragon/leaflet-drift-marker#7]
The slideTo() function slide as we expected.
But the endpoint is not accurate.
It slides until a position below the real target point.
For the same LatLng,
Leaflet set the market at real point, But slideTo() slides until a position below a real point.

How to fix that ?

**Comment by hugobarragon** [comment]
Hi, didnt get it, could you create a reproducible link,to compare?
use this template
https://codesandbox.io/s/static-bcdhq?fontsize=14

**Comment by Rehum02** [comment]
Hi. 
Thanks for reply.

In the codesandbox, all seem to work well.
On Click,  slideTo() slides until the clicked point,

But on my case, it slides until a near point of the clicked point.
Why that behaviour ?

My Code :
```
this.m_lieulivraison_place [opt ]. marker = new DriftMarker([pos.lat, pos.lng], {icon: marker_icon }).bindPopup("<div> " + msg_txt  +  "  </div>");
  
map.on('click', function(e) {
...
(this_.m_lieulivraison_place [opt ]. marker).slideTo( u_locate, {duration:1000, keepAtCenter:false});
...
})

```

**Comment by Rehum02** [comment]
Hi.

It was not an issue.
It was related to the icon size.
After setting anchor param, all was fine.


Thanks

**Comment by hugobarragon** [comment]
> Hi.
> 
> It was not an issue.
> It was related to the icon size.
> After setting anchor param, all was fine.
> 
> Thanks

great, that was what I was thinking about, custom icons normally needs some calibration 👍
