### ISSUE TITLE
Not working in Angular

### ISSUE THREAD

**Issue by Saqib92** [hugobarragon/leaflet-drift-marker#9]
facing this error: 

`Property 'addTo' does not exist on type 'DriftMarker'.ts(2339)`

**Comment by hugobarragon** [comment]
hello, please create a reproducible link at codesandbox  

here is working just fine  
https://codesandbox.io/s/static-bcdhq?fontsize=14&file=/index.html

**Comment by Saqib92** [comment]
I a using it in Ionic / Angular Project. and when i copy same code from your example. its show above mentioned Error. Will create reproducible Code.

**Comment by hugobarragon** [comment]
@Saqib92 here is angular with marker working link  
https://codesandbox.io/embed/angular-leaflet-leaflet-drift-marker-bywd6m?fontsize=14&hidenavigation=1&theme=dark

**Comment by Saqib92** [comment]
Looks Like Angular 13 Issue but not sure: 
Please Check this: https://stackblitz.com/edit/angular-ivy-ylbhvu

**Comment by hugobarragon** [comment]
can you please create a link with only angular and the leaflet map with a normal marker, the map does not seem to show correctly by it self  
![image](https://user-images.githubusercontent.com/35630927/165911965-10341cce-9cf3-434e-8c07-3ab43dacd9c4.png)

**Comment by hugobarragon** [comment]
@Saqib92 i found the problem, is within angular TS in this specific version its not recognizing the extension from marker, its only a typescript , not logical bug add this:    
` // @ts-ignore  ` before addTo
 
```
const marker = new DriftMarker([52.246215, 21.223158], {
      draggable: true,
      title: 'Resource location',
      alt: 'Resource Location',
      riseOnHover: true,
      icon: redMarker,
    })
      // @ts-ignore
      .addTo(map)
      
```

**Comment by Saqib92** [comment]
> @Saqib92 i found the problem, is within angular TS in this specific version its not recognizing the extension from marker, its only a typescript , not logical bug add this: `// @ts-ignore ` before addTo
> 
> ```
> const marker = new DriftMarker([52.246215, 21.223158], {
>       draggable: true,
>       title: 'Resource location',
>       alt: 'Resource Location',
>       riseOnHover: true,
>       icon: redMarker,
>     })
>       // @ts-ignore
>       .addTo(map)
>       
> ```

It worked. Thanks.
